# Generated by Django 3.1.6 on 2021-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210321_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
